spring:
  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: YOUR_SPOTIFY_CLIENT_ID
            client-secret: YOUR_SPOTIFY_CLIENT_SECRET
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - playlist-read-private
              - playlist-read-collaborative
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - https://www.googleapis.com/auth/youtube

server:
  port: 8080